### ISSUE TITLE
Write Readme

### ISSUE THREAD

**Issue by litetex** [litetex/PullDetachedRemote#2]
Should contain
* setup / how to use
* why to use
* build & develop yourself

**Comment by litetex** [comment]
Note: GITHUB_TOKEN is  NOT working!

Preview:
```YAML
...
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Pull Detached Remote
      uses: litetex/pull-detached-remote@vdev
      with:
        upstreamrepo: https://github.com/litetex/fork-base-test
        upstreambranch: an-update
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
```
