### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by litetex** [litetex/PullDetachedRemote#3]
Create how to test doc.

Should be something like this (but nicer 😄):
* Requires:
  * a base repo
  * a forked repo from base repo, but with no upstream
* Build the project
* Generate config yml
* Checkout forked into a dir
* Add checkedout fork into yml ``PathToWorkingRepo``
* Add ``BaseUpstreamRepo`` = CloneUrl of "base repo" and ``BaseUpstreamBranch``

If you want to test again, make sure to reset the checked out fork.

Examples:
Config:
```YML
IdentityEmail: test@test.test
IdentityUsername: TEST TEST
PathToWorkingRepo: D:\TEMP\forked-test
BaseOriginBranch: an-update
BaseUpstreamRepo: https://github.com/litetex/fork-base-test
BaseUpstreamBranch: an-update
NameOfOriginUpdateBranch: 
UpstreamRepoUseGitHubCreds: true
```

Reset.bat
```BAT
::Sometimes RemoveDir fails, so let's move the repo first
MOVE /Y forked-test forked-test-trash
RD /S /Q forked-test-trash
git clone https://github.com/litetex/forked-test
```

**Comment by litetex** [comment]
Changed...

**Comment by litetex** [comment]
Samples:

launchSettings.json
```JSON
{
  "profiles": {
    "PDR - GenConf": {
      "commandName": "Project",
      "commandLineArgs": "--genconf config.yml"
    },
    "PDR - Conf": {
      "commandName": "Project",
      "commandLineArgs": "--config config.yml --GITHUB_PAT=xxx"
    },
    "PDR - CMD": {
      "commandName": "Project",
      "commandLineArgs": "--identitymail=test@test.test --identityuser=\"Test Test\" --prlabels \"upstream\" --clonemode=CLONE_ALWAYS --originrepo=https://github.com/<owner>/forked --originbranch=an-update --upstreamrepo=https://github.com/<owner>/fork-base --upstreambranch=master --GITHUB_PAT=xxx"
    }
  }
}
```

config.yml
```YML
IdentityEmail: test@test.test
IdentityUsername: Test Test
PRMetaInfo:
  Assignees: []
  Reviewers: []
  Labels: ['upstream']
PathToWorkingRepo: test
CloneMode: CLONE_ALWAYS
OriginRepo: https://github.com/<owner>/forked
OriginBranch: an-update
UpstreamRepo: https://github.com/<owner>/fork-base
UpstreamBranch: master
OriginUpdateBranch: 
UpstreamCredMode: AUTO
```
